version: '3'
services:
  web:
    build: .
    ports:
      - "8080:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      timeout: 10s
